# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cache_app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cache_app

pod 'Firebase/Core'

pod 'Firebase/Auth’

pod 'Firebase/Database'

pod 'Charts'

  target 'cache_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cache_appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
